name: Create Issue When User Accepts Org Invitation

on:
  push:
    branches:
      - main
  member:
    types: [added]

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the user is part of the organization
        id: check_user
        run: |
          echo "Checking if the user is part of the organization..."
          USERNAME="${{ github.event.member.login }}"
          ORG="demo-0987"   # Replace with your organization name
          
          # Use GitHub API to check if user is part of the organization
          ORG_MEMBER=$(curl -s -H "Authorization: token ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/orgs/${ORG}/members/${USERNAME}")
          
          if echo "$ORG_MEMBER" | grep -q "Not Found"; then
            echo "User is not a member of the organization yet. Exiting..."
            exit 0
          else
            echo "User is a member of the organization."
          fi

      - name: Create an Issue in the Invitation repository
        if: success()
        run: |
          USERNAME="${{ github.event.member.login }}"
          ORG="demo-0987"
          REPO="Invitation-repository"
          TITLE="New User Joined: $USERNAME"
          BODY="The user @$USERNAME has accepted the invitation to join the organization and is now a member of the repository."

          curl -X POST \
            -H "Authorization: token ${{ secrets.TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${ORG}/${REPO}/issues \
            -d "$(jq -n --arg title "$TITLE" --arg body "$BODY" '{title: $title, body: $body}')"

            
