name: Create Issues for New Org Members

on:
  schedule:
    - cron: '*/10 * * * *'  # every 10 minutes

jobs:
  create-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Get current org members
        run: |
          curl -s -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/orgs/demo-0987/members > members.json

      - name: Prepare previous members list
        run: |
          if [ ! -f previous_members.txt ]; then
            touch previous_members.txt
          fi

      - name: Detect new members and create issues
        run: |
          current=$(jq -r '.[].login' members.json | sort)
          previous=$(cat previous_members.txt | sort)

          new_members=$(comm -13 <(echo "$previous") <(echo "$current"))

          echo "New members detected:"
          echo "$new_members"

          for user in $new_members; do
            echo "Creating issue for $user"
            payload=$(jq -n --arg user "$user" --arg org "demo-0987" '{
              title: ("Welcome " + $user + " to " + $org),
              body: ("User @" + $user + " has accepted the invitation to the organization.")
            }')

            curl -X POST \
              -H "Authorization: token ${{ secrets.GH_PAT }}" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/repos/demo-0987/Invitation-repository/issues \
              -d "$payload"
          done

          echo "$current" > previous_members.txt

      - name: Commit updated members list
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add previous_members.txt
          git commit -m "Update members list"
          git push
        continue-on-error: true
