name: Create Issue on Collaborator Added or Push

on:
  member:
    types: [added]
  push:
    branches:
      - main

jobs:
  create-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the user is collaborator
        id: check_user
        run: |
          echo "Checking if the user is collaborator..."
          USERNAME=${{ github.event.member.login || '' }}
          ORG="demo-0987"
          REPO="Invitation-repository"

          # If USERNAME is empty (e.g. on push), skip
          if [ -z "$USERNAME" ]; then
            echo "No user to check (probably triggered by push)."
            echo "user_is_collaborator=false" >> $GITHUB_OUTPUT
            exit 0
          fi

          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" \
            -H "Authorization: token ${{ secrets.TOKEN }}" \
            "https://api.github.com/repos/${ORG}/${REPO}/collaborators/${USERNAME}")

          if [ "$RESPONSE" = "204" ]; then
            echo "User $USERNAME is a collaborator."
            echo "user_is_collaborator=true" >> $GITHUB_OUTPUT
          else
            echo "User $USERNAME is NOT a collaborator."
            echo "user_is_collaborator=false" >> $GITHUB_OUTPUT
          fi

      - name: Create Issue for New Collaborator
        if: steps.check_user.outputs.u_

