name: Invite User and Create Issue on Acceptance

on:
  workflow_dispatch:
    inputs:
      username:
        description: 'GitHub username to invite'
        required: true
      issue_title:
        description: 'Issue summary/title'
        required: true
      issue_body:
        description: 'Issue description/body'
        required: true

jobs:
  invite-and-create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Invite user to demo-0987 organization
        run: |
          echo "Inviting user ${{ github.event.inputs.username }} to org demo-0987..."
          curl -X PUT \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/orgs/demo-0987/memberships/${{ github.event.inputs.username }} \
            -d '{"role":"direct_member"}'

      - name: Wait for user to accept invitation (up to 30 minutes)
        run: |
          echo "Waiting for ${{ github.event.inputs.username }} to accept the invitation..."
          accepted="false"
          for i in {1..60}; do
            sleep 30
            response=$(curl -s \
              -H "Authorization: token ${{ secrets.GH_PAT }}" \
              -H "Accept: application/vnd.github+json" \
              https://api.github.com/orgs/demo-0987/members)

            echo "$response" | grep -q "\"login\": \"${{ github.event.inputs.username }}\""
            if [ $? -eq 0 ]; then
              echo "User has accepted the invitation"
              accepted="true"
              break
            else
              echo "Still waiting..."
            fi
          done

          if [ "$accepted" != "true" ]; then
            echo "User did not accept the invitation within 30 minutes"
            exit 1
          fi

      - name: Create issue in demo-0987/Invitation-repository
        run: |
          echo "Creating issue in Invitation-repository..."
          curl -X POST \
            -H "Authorization: token ${{ secrets.GH_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/demo-0987/Invitation-repository/issues \
            -d @- <<EOF
          {
            "title": "${{ github.event.inputs.issue_title }}",
            "body": "${{ github.event.inputs.issue_body }}"
          }
          EOF
